### ISSUE TITLE
Lighthouse report

### ISSUE THREAD

**Issue by stevepeak** [asyncy/asyncy.com#26]
<img width="544" alt="screen shot 2018-05-17 at 9 55 52 am" src="https://user-images.githubusercontent.com/2041757/40163968-88d54a24-59b8-11e8-89d6-0181537648d3.png">

There are a number of issues that we should look at resolving. 

I ran this with [Lighthouse](https://developers.google.com/web/tools/lighthouse/#devtools)

**Comment by abylaw** [comment]
Much better:
![image](https://user-images.githubusercontent.com/1841215/40863789-1df18a7a-65bf-11e8-98d0-59a5e17cf244.png)

https://lighthouse--asyncy-homepage.netlify.com/

**Comment by stevepeak** [comment]
Very Nice 👍
